#!/bin/ash

# This file is part of initsystem
#
# Copyright (C) 2014-2017 Valère Monseur (valere dot monseur at ymail dot com)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

read -r rc_if 2>/dev/null < "/etc/$(basename "$0").interface"
[ "${rc_if}" ] || { echo "missing or incorrect /etc/$(basename "$0").interface"; exit 1; }

rc_cmd="/usr/bin/dhcpcd -q -w ${rc_if}"
rc_stop_cmd="/usr/bin/dhcpcd -q -x ${rc_if}"

. /etc/rc.conf
. /etc/rc.subr

rc_run "start stop restart status" $@
