#!/bin/ash

# This file is part of initsystem
#
# Copyright (C) 2015-2017 Valère Monseur (valere dot monseur at ymail dot com)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

[ -f /etc/conf.d/lm_sensors ] || { echo "missing /etc/conf.d/lm_sensors"; exit 1; }
. /etc/conf.d/lm_sensors

. /etc/rc.conf
. /etc/rc.subr

start() {
  /usr/bin/modprobe -a -b -s "${BUS_MODULES}" "${HWMON_MODULES}"
  /usr/bin/sensors -s
}

stop() {
  /usr/bin/modprobe -a -b -s -r "${BUS_MODULES}" "${HWMON_MODULES}" || return 0
}

display() {
  /usr/bin/sensors
}

rc_run "start stop display" $@

# vim: set filetype=sh:
