post_install() {
  printf '==> You have to configure the init system in /etc/rc.conf\n'
  printf '    You can optionally define extra startup commands in /etc/rc.local\n'
  printf '    You can optionally define extra shutdown commands in /etc/rc.shutdown.local\n'

  if grep -q init-og /proc/1/comm; then
    # ask init (pid 1) to re-exec itself
    kill -QUIT 1
  fi
}

post_upgrade() {
  if grep -q init-og /proc/1/comm; then
    # ask init (pid 1) to re-exec itself
    kill -QUIT 1
  fi
}
