#!/usr/bin/ash

# This file is part of initsystem
#
# Copyright (C) 2014 Valère Monseur (valere dot monseur at ymail dot com)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -u

PATH="/opt/busybox"
export PATH

################################################################################
# sanity check #################################################################
################################################################################

if [ $(id -u) != 0 ]; then
  echo "error: this script should be run as root"
  exit 1
fi

################################################################################
# shutdown #####################################################################
################################################################################

case `basename $0` in
  halt)
    kill -12 1 # SIGUSR2
    ;;
  poweroff)
    kill -15 1 # SIGTERM
    ;;
  reboot)
    kill -10 1 # SIGUSR1
    ;;
  *)
    echo "usage: halt|poweroff|reboot"
    exit 1
    ;;
esac

exit 0
