#!/bin/ash

# This file is part of initsystem
#
# Copyright (C) 2014-2016 Valère Monseur (valere dot monseur at ymail dot com)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

PATH=/opt/busybox
LC_ALL=C

export PATH LC_ALL

################################################################################
# sanity check #################################################################
################################################################################

if [ $(id -u) != 0 ]; then
  echo "error: this script should be run as root"
  exit 1
fi

################################################################################
# shutdown #####################################################################
################################################################################

case $(basename "$0") in
  halt)     kill -USR2 1 ;;
  poweroff) kill -TERM 1 ;;
  reboot)   kill -USR1 1 ;;
  shutdown)
    case "$1" in
      -h) kill -USR2 1 ;;
      -p) kill -TERM 1 ;;
      -r) kill -USR1 1 ;;
      *)
        echo "usage: shutdown {-h|-p|-r}"
        exit 1
        ;;
    esac
    ;;
  *)
    echo "usage: {halt|poweroff|reboot|shutdown}"
    exit 1
    ;;
esac

exit 0
