#!/bin/bash

DIR="$(dirname "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")"

make -C "$DIR"/initsystem dist
mv -f "$DIR"/initsystem/initsystem.tar.gz "$DIR"/archlinux
cd "$DIR"/archlinux && makepkg -cf --skipchecksums

# vim: set filetype=sh:
