#!/bin/ash

rc_start_cmd="/usr/bin/dbus-daemon --system --fork --nopidfile --syslog-only"

rc_pre_start() {
  /usr/bin/install -d -m755 -o dbus -g dbus /run/dbus
}

. /etc/rc.d/rc.subr

rc_run "start stop restart reload status" $@

# vim: set filetype=sh:
