#!/bin/ash

rc_start_cmd="/usr/bin/haveged -w 1024 -v 0 2>/dev/null"

rc_pre_start() {
  /usr/bin/sysctl -q -w kernel.random.write_wakeup_threshold=1024
}

. /etc/rc.d/rc.subr

rc_run "start stop restart status" $@

# vim: set filetype=sh:
