#!/bin/ash

rc_start_cmd="/usr/bin/haveged"

rc_pre_start() {
  /usr/bin/sysctl -q -w kernel.random.write_wakeup_threshold=1024
  rc_output="2>/dev/null" # avoid annoying output
}

. /etc/rc.d/rc.subr

rc_run "start stop restart status" $@

# vim: set filetype=sh:
