#!/bin/ash

rc_type="nodaemon"

rc_start_cmd="/usr/bin/ip6tables-restore /etc/iptables/ip6tables.rules"
rc_reload_cmd="/usr/bin/ip6tables-restore /etc/iptables/ip6tables.rules"
rc_stop_cmd="PATH=/usr/bin /usr/lib/systemd/scripts/iptables-flush 6 1>/dev/null"
rc_display_cmd="/usr/bin/ip6tables -L -v -n --line-numbers"

. /etc/rc.d/rc.subr

rc_run "start stop restart reload display" $@

# vim: set filetype=sh:
