#!/bin/ash

rc_type="nodaemon"

rc_start_cmd="/usr/bin/sensors -s"
rc_display_cmd="/usr/bin/sensors"

rc_pre_start() {
  . /etc/conf.d/lm_sensors
  /usr/bin/modprobe -a -b -s ${BUS_MODULES} ${HWMON_MODULES}
}

. /etc/rc.d/rc.subr

rc_run "start display" $@

# vim: set filetype=sh:
