#!/bin/ash

rc_type="nodaemon"
rc_env="PATH=/usr/bin"
rc_output="1>/dev/null"

rc_start_cmd="/usr/bin/tlp init start"
rc_stop_cmd="/usr/bin/tlp init stop"
rc_display_cmd="/usr/bin/tlp-stat"

. /etc/rc.d/rc.subr

rc_run "start stop restart display" $@

# vim: set filetype=sh:
