#!/bin/ash

rc_start_cmd="/usr/lib/systemd/systemd-udevd --daemon"
rc_reload_cmd="/usr/bin/udevadm control --reload"
rc_stop_cmd="/usr/bin/udevadm control --exit"

init() { # run by /etc/rc at startup time _after_ start
  STATUS=0

  /usr/bin/udevadm trigger --action=add --type=subsystems || STATUS=1
  /usr/bin/udevadm trigger --action=add --type=devices || STATUS=1
  /usr/bin/udevadm settle || STATUS=1

  return $STATUS
}

. /etc/rc.d/rc.subr

rc_run "start init stop restart reload status" $@

# vim: set filetype=sh:
