#!/bin/bash

export LC_ALL=C

scandir() {
  for FILE in `find "$1"`; do
    LIBRARY=`readelf -d "${FILE}" 2>/dev/null | grep library | grep "$2" | cut -d ':' -f 2 | tr -d '[]'`

    if [ "${LIBRARY}" -a "${LIBRARY}" != " " ]; then
      PACKAGE=`pacman -Qqo "${FILE}"`
      echo "${LIBRARY} ${PACKAGE} ${FILE}"
    fi
  done
}

if [ $# -ne 1 ]; then
  echo "usage: `basename $0` id_to_scan"
  echo "example: `basename $0` systemd"
  exit 1
fi

echo ""
echo "scanning for $1 in /usr/bin"
echo ""

scandir "/usr/bin" "$1"

echo ""
echo "scanning for $1 in /usr/lib"
echo ""

scandir "/usr/lib" "$1"

echo ""
echo "scanning for $1 in /usr/lib32"
echo ""

scandir "/usr/lib32" "$1"

exit 0
