#!/bin/bash

export LC_ALL=C

if [ $(id -u) -ne 0 ]; then
  echo "error: this script should be run as root"
  exit 1
fi

searchfile() {
  LIBRARY=$(readelf -d "$1" 2>/dev/null | grep library | grep "$2" | cut -d ':' -f 2 | tr -d '[]' | tr -d ' ')

  if [ "${LIBRARY}" -a "${LIBRARY}" != "" ]; then
    PACKAGE=$(pkgfile "$1")
    echo "library ${LIBRARY} used by file $1 contained in package ${PACKAGE}"
  fi
}

searchdirectory() {
  for FILE in $(find "$1" -type f); do
    searchfile "${FILE}" "$2"
  done
}

case $# in
  1)
    for DIRECTORY in /usr/bin /usr/lib /usr/lib32; do
      echo ""
      echo "scanning for $1 in ${DIRECTORY}"
      echo ""

      searchdirectory "${DIRECTORY}" "$1" | sort -k2 | column -t -o ' '
    done
    ;;
  2)
    searchfile "$2" "$1"
    ;;
  *)
    echo "usage: $(basename "$0") identifier <file>"
    exit 1
    ;;
esac

exit 0
