#!/bin/bash

if [ $(id -u) -eq 0 ]; then
  echo "error: this script should not be run as root"
  exit 1
fi

case "$1" in
  initsystem|systemd)
    vboxmanage startvm archlinux-"$1"
    ;;
  *)
    echo "usage: $(basename $0) initsystem|systemd"
    exit 1
    ;;
esac
