#!/bin/bash

# TODO: avoid harcoded paths

if [ $(id -u) -ne 0 ]; then
  echo "error: this script should be run as root"
  exit 1
fi

PACKAGES_SYSTEMD="
../initsystem/busybox/busybox-1.29.1-1-x86_64.pkg.tar.xz
../initsystem/initsystem/archlinux/initsystem-1.2.0-1-x86_64.pkg.tar.xz
"

PACKAGES_INITSYSTEM="
${PACKAGES_SYSTEMD}
../initsystem/eudev/eudev-3.2.5-1-x86_64.pkg.tar.xz
../initsystem/opentmpfiles/opentmpfiles-0.1.3-1-any.pkg.tar.xz
../initsystem/systemd/systemd-239.0-2-any.pkg.tar.xz
../pkgbuild/core/dbus/dbus-1.12.8-1-x86_64.pkg.tar.xz
../pkgbuild/core/procps-ng/procps-ng-3.3.15-1-x86_64.pkg.tar.xz
../pkgbuild/core/util-linux/libutil-linux-2.32.1-1-x86_64.pkg.tar.xz
../pkgbuild/core/util-linux/util-linux-2.32.1-1-x86_64.pkg.tar.xz
../pkgbuild/extra/syslog-ng/syslog-ng-3.15.1-3-x86_64.pkg.tar.xz
"

case "$1" in
  initsystem)
    IMAGE="/home/valr/document/system/vbox/archlinux-$1/archlinux-$1.vdi"
    PACKAGES="${PACKAGES_INITSYSTEM}"
    ;;
  systemd)
    IMAGE="/home/valr/document/system/vbox/archlinux-$1/archlinux-$1.vdi"
    PACKAGES="${PACKAGES_SYSTEMD}"
    ;;
  *)
    echo "usage: $(basename "$0") initsystem|systemd"
    exit 1
    ;;
esac

for FILE in "${IMAGE}" ${PACKAGES}; do
  if [ ! -e "${FILE}" ]; then
    echo "error: the file ${FILE} does not exist"
    exit 1
  fi
done

if ps ax | grep [a]rchlinux-"$1" &>/dev/null; then
  echo "error: the virtual machine is running"
  exit 1
fi

wait_device() {
  for i in $(seq $2); do
    if [ -e "$1" ]; then
      return 0
    fi

    sleep .25
  done

  return 1
}

DEVICE="/dev/nbd0"
PARTITION_ROOT="/dev/nbd0p2"
PARTITION_BOOT="/dev/nbd0p1"
ROOT="/mnt"

qemu-nbd -c "${DEVICE}" "${IMAGE}"
partx -a "${DEVICE}"

wait_device "${PARTITION_ROOT}" 40 && mount -t ext4 "${PARTITION_ROOT}" "${ROOT}"
wait_device "${PARTITION_BOOT}" 40 && mount -t vfat "${PARTITION_BOOT}" "${ROOT}"/boot

pacman -U \
  --dbpath   "${ROOT}"/var/lib/pacman/ \
  --root     "${ROOT}"/ \
  --cachedir "${ROOT}"/var/cache/pacman/pkg/ \
  --config   "${ROOT}"/etc/pacman.conf \
  --gpgdir   "${ROOT}"/etc/pacman.d/gnupg/ \
  --hookdir  "${ROOT}"/usr/share/libalpm/hooks/ \
  --logfile  "${ROOT}"/var/log/pacman.log \
  --noconfirm \
  --noscriptlet \
  ${PACKAGES}

cp -f ${PACKAGES} "${ROOT}"/root

sync

umount "${ROOT}"/boot
umount "${ROOT}"

qemu-nbd -d "${DEVICE}"

exit 0

# qemu-nbd -c /dev/nbd0 "/home/valr/document/system/vbox/archlinux-initsystem/archlinux-initsystem.vdi"
# partx -a /dev/nbd0
# mount -t ext4 /dev/nbd0p2 /mnt
# mount -t vfat /dev/nbd0p1 /mnt/boot
# chroot /mnt /bin/bash
# umount /mnt/boot
# umount /mnt
# qemu-nbd -d /dev/nbd0
