#!/bin/sh

# TODO: rework this ugly script

rm -f initsystem.tar.gz

( cd ..; make clean; make dist; mv initsystem.tar.gz archlinux; )

makepkg -f --skipchecksums

rm -f initsystem.tar.gz

# vim: set filetype=sh:
